#
# Dockerfile for package-lock.json build
#

ARG NODE_VERSION_ARG

FROM node:$NODE_VERSION_ARG-alpine

WORKDIR /root

COPY ./package.json ./

RUN npm install
RUN npm dedupe
RUN npm audit fix
RUN npm audit
